#!/bin/bash -l
#
# submit like this: sbatch.tinygpu jobscript.slurm
#
#SBATCH --ntasks=32
##SBATCH --nodes=1
# walltime
#SBATCH --time=23:59:00
#
# mail to user
#SBATCH --mail-user=hermann.luft@fau.de
#SBATCH --mail-type=ALL
#
# job name (No Spaces!)
#SBATCH --job-name=Hepatitis_outlier_results

# load module
module load python/3.9-anaconda
conda activate env_ireos

cd /home/hpc/iwso/iwso070h/results/ireos

python main.py Hepatitis_withoutdupl_norm_05_v01
python main.py Hepatitis_withoutdupl_norm_05_v02
python main.py Hepatitis_withoutdupl_norm_05_v03
python main.py Hepatitis_withoutdupl_norm_05_v04
python main.py Hepatitis_withoutdupl_norm_05_v05
python main.py Hepatitis_withoutdupl_norm_05_v06
python main.py Hepatitis_withoutdupl_norm_05_v07
python main.py Hepatitis_withoutdupl_norm_05_v08
python main.py Hepatitis_withoutdupl_norm_05_v09
python main.py Hepatitis_withoutdupl_norm_05_v10
